name: Validate Android

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - '.editorconfig'

jobs:
  lint:
    name: Gradle Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example/android
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install --frozen-lockfile --cwd ../..
      - name: Install node_modules for example/
        run: yarn install --frozen-lockfile --cwd ..

      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Lint
        run: ./gradlew lint --build-cache

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: example/android/build/reports/lint-results.xml
